### ISSUE TITLE
Text Displacement Issue

### ISSUE THREAD

**Issue by Ftonans** [Insprill/intellectual#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of Intellectual?

- [X] I am using the latest version of Intellectual.

### Describe the bug

This issue occurs with songs that have long names. ~It occurs only on the desktop version of the website.~
![Screenshot_20230913-110501](https://github.com/Insprill/intellectual/assets/77411099/18357a81-80f4-4364-b5a9-c6af274e1cb5)
![Screenshot_20230913-110451](https://github.com/Insprill/intellectual/assets/77411099/c985d532-d522-4fbc-ac33-fe5812f8a03a)
![image](https://github.com/Insprill/intellectual/assets/77411099/e36c85e7-e392-4a7d-b2b1-59fb947f7872)
![image](https://github.com/Insprill/intellectual/assets/77411099/72a47002-6c27-47b9-bd8c-88da2a813309)

### Anything else?

https://in.bloatcat.tk/lyrics?path=/2-bi-2-nobody-writes-to-the-colonel-lyrics&id=3453476
https://in.bloatcat.tk/search?q=%D0%B1%D0%B82+%D0%BF%D0%BE%D0%BB%D0%BA%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA%D1%83+%D0%BD%D0%B8%D0%BA%D1%82%D0%BE+%D0%BD%D0%B5+%D0%BF%D0%B8%D1%88%D0%B5%D1%82

**Comment by Insprill** [comment]
I've known about this for awhile, but I'm not the best with CSS so I'm not sure exactly how to fix it. If anyone does please feel free to make a PR!
