### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by Ftonans** [Insprill/intellectual#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It would be nice to have support for the musl library for the binaries because I have to recompile it with every release. You can consider using this tool for that purpose: [cross](https://github.com/cross-rs/cross)

**Comment by Insprill** [comment]
Are you looking for that in a Docker container or released as a pre-built binary? If it's the latter, we can just add it to the CI pipeline.

**Comment by Insprill** [comment]
Added musl builds to the pipeline in 4c9bab469e256c69e0ec040c49bf8bae222884eb.
