### ISSUE TITLE
Add instance intellectual.catsarch.com

### ISSUE THREAD

**Issue by ButteredCats** [Insprill/intellectual#19]
### URL

https://intellectual.catsarch.com

### Region

US

### Cloudflare

- [ ] Is the instance proxied behind Cloudflare?

**Comment by Insprill** [comment]
I'm getting a 403 Forbidden when applying settings. Make sure POST requests are allowed to `/settings`

**Comment by ButteredCats** [comment]
Whoops, that's fixed now.

**Comment by Insprill** [comment]
Added in 4a2ecee568d38dd9f2f9b4f2762d4e1dabe67435, thank you!
