### ISSUE TITLE
Add Tor instance intellectual.catsarchywsyuss6jdxlypsw5dc7owd5u5tr6bujxb7o6xw2hipqehyd.onion

### ISSUE THREAD

**Issue by ButteredCats** [Insprill/intellectual#20]
### URL

http://intellectual.catsarchywsyuss6jdxlypsw5dc7owd5u5tr6bujxb7o6xw2hipqehyd.onion

### Region

US

### Cloudflare

- [ ] Is the instance proxied behind Cloudflare?

**Comment by Insprill** [comment]
Added in 4a2ecee568d38dd9f2f9b4f2762d4e1dabe67435
