### ISSUE TITLE
Page Not Found for lyrics that exist in Genius

### ISSUE THREAD

**Issue by ButteredCats** [Insprill/intellectual#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of Intellectual?

- [X] I am using the latest version of Intellectual.

### Describe the bug

I've found a song that exists on Genius but can't be visited within Intellectual. Trying to visit it just results in "Page Not Found"

### Anything else?

Song on Genius: https://genius.com/Ck9c-the-end-of-times-annotated
Song on Intellectual:  https://intellectual.catsarch.com/Ck9c-the-end-of-times-annotated

**Comment by Insprill** [comment]
That URL is wrong. It should be https://intellectual.catsarch.com/lyrics?path=Ck9c-the-end-of-times-annotated. I've thought about changing it so the URL's match Genius, then redirects would only need to change the host.

**Comment by ButteredCats** [comment]
Oh whoops. Libredirect sent me there so I didn't even question the path. Guess I havent actually been redirected to Intellectual by it until now. Sorry about that!
